console: Gracefully handle when setups are not active
➜  ~ yo console
Traceback (most recent call last):
  File "/home/leonro/src/yo/yo", line 24, in <module>
    utils.cmdline.main(cmd_modules, plugins)
  File "/home/leonro/src/yo/utils/cmdline.py", line 133, in main
    args.func(args)
  File "/home/leonro/src/yo/plugins/cmd_console.py", line 21, in cmd_console
    choice = questionary.select("Which server to connect?", players).ask()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/questionary/prompts/select.py", line 121, in select
    raise ValueError("A list of choices needs to be provided.")
ValueError: A list of choices needs to be provided.

Signed-off-by: Leon Romanovsky <leon@kernel.org>