verify: Fix wrong branch when push to gerrit
Enumerating objects: 17, done.
Counting objects: 100% (17/17), done.
Delta compression using up to 16 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (9/9), 855 bytes | 855.00 KiB/s, done.
Total 9 (delta 7), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (7/7)
remote: Processing changes: refs: 1, done
To ssh://l-gerrit.mtl.labs.mlnx:29418/upstream/linux
 ! [remote rejected]           HEAD -> refs/for/xfrm-next%topic=leon_testing (branch xfrm-next not found)
error: failed to push some refs to 'ssh://l-gerrit.mtl.labs.mlnx:29418/upstream/linux'

Fixes: 4bf7318e42dc ("Initial commit")
Signed-off-by: Leon Romanovsky <leonro@nvidia.com>